import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { checkAdminAuth } from "@/lib/admin-auth";

export const dynamic = "force-dynamic";

const ARCHITECTS = [
  {
    name: "Alister MacKenzie",
    slug: "alister-mackenzie",
    bornYear: 1870,
    diedYear: 1934,
    nationality: "British",
    era: "Golden Age",
    totalCoursesDesigned: 52,
    bio: "Dr. Alister MacKenzie was a British golf course architect whose designs are widely regarded as among the finest ever created. Born in Normanton, Yorkshire, he initially trained as a surgeon and served in the Boer War, where he observed how Boer fighters used natural camouflage — an insight that profoundly influenced his approach to golf design. MacKenzie believed courses should appear natural and that hazards should be visible yet strategically demanding. He partnered with Bobby Jones to create Augusta National Golf Club, home of The Masters, and designed Cypress Point Club on the Monterey Peninsula, often cited as the most beautiful course in the world. His international portfolio includes Royal Melbourne West in Australia and Pasatiempo in California. MacKenzie authored 'The Spirit of St. Andrews,' outlining his 13 principles of golf architecture that remain influential today.",
    designPhilosophy: "MacKenzie championed strategic design where every hole offered multiple routes of varying risk and reward. He believed a course should be enjoyable for all skill levels while providing the sternest test for the expert. His mantra was that artificial features should mimic nature so closely that they appear to have always existed.",
    signatureCourses: ["Augusta National", "Cypress Point Club", "Royal Melbourne West", "Pasatiempo", "Crystal Downs"],
    notableFeatures: ["Bold, sprawling bunker complexes", "Contoured greens with subtle slopes", "Strategic routing through natural terrain", "Camouflage principles applied to hazards"],
  },
  {
    name: "Donald Ross",
    slug: "donald-ross",
    bornYear: 1872,
    diedYear: 1948,
    nationality: "Scottish-American",
    era: "Golden Age",
    totalCoursesDesigned: 413,
    bio: "Donald James Ross was a Scottish-born American golf course architect who shaped the landscape of American golf more than perhaps any other designer. Born in Dornoch, Scotland, he apprenticed under Old Tom Morris at St Andrews before emigrating to the United States in 1899. Ross settled in Pinehurst, North Carolina, where he transformed the resort's No. 2 course into one of America's most celebrated layouts. His prolific career spanned nearly five decades, during which he designed or redesigned over 400 courses across North America. Ross's signature crowned, convex putting surfaces became his hallmark — these 'inverted saucer' greens reject wayward approach shots and demand precision. Pinehurst No. 2 hosted the 2014 U.S. Open and U.S. Women's Open in consecutive weeks, cementing its status as a national treasure. Seminole Golf Club, Oakland Hills, and East Lake Golf Club further showcase his brilliance.",
    designPhilosophy: "Ross believed in creating courses that were fair but demanding, where the player who thought most clearly and executed most precisely would prevail. His greens complexes are the heart of his designs — crowned surfaces surrounded by collection areas that make recovery shots a true test of skill. He favored natural landforms and minimal earth-moving.",
    signatureCourses: ["Pinehurst No. 2", "Seminole Golf Club", "Oakland Hills South", "East Lake Golf Club", "Aronimink"],
    notableFeatures: ["Crowned/inverted saucer greens", "Subtle mounding around greens", "Natural integration with existing terrain", "Strategic bunkering at green approaches"],
  },
  {
    name: "Pete Dye",
    slug: "pete-dye",
    bornYear: 1925,
    diedYear: 2020,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 100,
    bio: "Paul 'Pete' Dye was an American golf course architect who revolutionized modern golf design with his daring, visually intimidating layouts. Born in Urbana, Ohio, Dye was a successful amateur golfer and insurance salesman before turning to course design full-time. After a transformative trip to Scotland with his wife Alice — herself an accomplished designer — Dye incorporated links-style features like railroad ties, pot bunkers, and waste areas into American courses. His TPC Sawgrass in Ponte Vedra Beach, Florida, with its iconic island green 17th hole, became the most famous par-3 in golf and revolutionized stadium golf course design. Whistling Straits in Wisconsin, built on a flat Lake Michigan shoreline transformed to mimic Irish links, hosted multiple PGA Championships and the 2021 Ryder Cup. Dye's courses are psychological as much as physical challenges, using visual deception to test nerve and strategy.",
    designPhilosophy: "Dye believed golf should be a mental battle as much as a physical one. His designs use dramatic visual intimidation — steep railroad ties, severe bunkers, and water carries that appear more treacherous than they are. He often said his courses play easier than they look, but few players believe him. His wife Alice Dye advocated for forward tees and inclusive design.",
    signatureCourses: ["TPC Sawgrass (Stadium)", "Whistling Straits", "Harbour Town Golf Links", "Kiawah Island (Ocean)", "Teeth of the Dog"],
    notableFeatures: ["Railroad tie bulkheads", "Island greens and dramatic water features", "Visual intimidation and optical illusions", "Links-style waste bunkers in non-links settings"],
  },
  {
    name: "Tom Fazio",
    slug: "tom-fazio",
    bornYear: 1945,
    diedYear: null,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 130,
    bio: "Tom Fazio is one of the most prolific and commercially successful golf course architects in history. Born in Norristown, Pennsylvania, he learned the craft working alongside his uncle George Fazio before establishing his own firm. Fazio's courses consistently appear atop America's best lists — Shadow Creek in Las Vegas, carved from flat desert terrain into a lush oasis, demonstrated his ability to create extraordinary golf landscapes from nothing. His meticulous attention to aesthetics, playability, and conditioning has made him the preferred architect for elite private clubs. Wade Hampton in the mountains of North Carolina and Calusa Pines in Naples, Florida, showcase his range across different landscapes. Fazio has more courses ranked in Golf Digest's Top 100 than any other living architect, and his renovation work at iconic venues like Merion and Quail Hollow has earned widespread acclaim.",
    designPhilosophy: "Fazio prioritizes the total golf experience — beauty, playability, and enjoyment for members of all skill levels. His routing philosophy emphasizes dramatic elevation changes, pristine conditioning, and courses that challenge without punishing. He believes golf should be visually stunning from every angle and that a great course makes every golfer feel they played well.",
    signatureCourses: ["Shadow Creek", "Wade Hampton", "Calusa Pines", "Querencia", "National Golf Links of America (renovation)"],
    notableFeatures: ["Dramatic elevation changes", "Pristine visual aesthetics", "Generous fairways with strategic bunkering", "Seamless integration with upscale club environments"],
  },
  {
    name: "Jack Nicklaus",
    slug: "jack-nicklaus",
    bornYear: 1940,
    diedYear: null,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 425,
    bio: "Jack William Nicklaus, the greatest golfer who ever lived with 18 major championship victories, has built an equally remarkable second career as one of the world's most prolific golf course designers. Through Nicklaus Design, he has created courses in 45 countries across six continents. Muirfield Village in Dublin, Ohio — host of The Memorial Tournament he founded — is widely considered his masterpiece and reflects his belief that every hole should be a complete strategic puzzle. His international portfolio includes prestigious venues like Monte Montgomery in Montenegro, The Bear's Club in Jupiter, Florida, and Cabo del Sol in Mexico. Nicklaus brings a champion's perspective to design, creating courses that test elite players while remaining playable for amateurs through multiple tee options. His renovation of the Ocean Course at Cabo del Sol and the design of Valhalla Golf Club (host of multiple PGA Championships) further demonstrate his range.",
    designPhilosophy: "Nicklaus designs from a champion's perspective — he creates strategic challenges that reward precise shot-making and course management. He believes par should be easy to achieve but birdie should require excellence. His courses feature well-defined risk-reward opportunities and multiple tee boxes to ensure playability across all skill levels.",
    signatureCourses: ["Muirfield Village", "Valhalla", "The Bear's Club", "Cabo del Sol (Ocean)", "Shoal Creek"],
    notableFeatures: ["Strategic risk-reward par 5s", "Well-defined hole corridors", "Multiple teeing options for all levels", "Championship-caliber finishing holes"],
  },
  {
    name: "Robert Trent Jones Sr.",
    slug: "robert-trent-jones-sr",
    bornYear: 1906,
    diedYear: 2000,
    nationality: "British-American",
    era: "Post-War",
    totalCoursesDesigned: 500,
    bio: "Robert Trent Jones Sr. was the most influential golf course architect of the mid-20th century, earning the title 'The Open Doctor' for his work upgrading major championship venues. Born in Ince, England, he emigrated to the United States as a child and created his own degree program at Cornell University combining landscape architecture, agronomy, and engineering — essentially inventing the modern golf architecture curriculum. Jones designed or remodeled more than 500 courses in 45 states and 35 countries. His philosophy of 'hard par, easy bogey' defined an era of championship golf design. Spyglass Hill on the Monterey Peninsula, Firestone South in Akron, and Peachtree Golf Club (co-designed with Bobby Jones) are among his most celebrated works. He toughened Oakland Hills for the 1951 U.S. Open so severely that Ben Hogan famously called it 'the monster.'",
    designPhilosophy: "Jones believed in 'hard par, easy bogey' — courses should reward excellent shots with birdie opportunities while punishing mediocre ones with bogey, but never making the game impossible for average players. He favored large, dramatically contoured greens, heroic water carries, and elevated tees that frame each hole as a distinct visual and strategic challenge.",
    signatureCourses: ["Spyglass Hill", "Firestone South", "Peachtree Golf Club", "Hazeltine National", "Valderrama"],
    notableFeatures: ["Large, dramatically contoured greens", "Heroic water carries", "Elevated championship tees", "'Hard par, easy bogey' philosophy"],
  },
  {
    name: "Robert Trent Jones Jr.",
    slug: "robert-trent-jones-jr",
    bornYear: 1939,
    diedYear: null,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 280,
    bio: "Robert Trent Jones Jr. continued his father's legacy while developing his own distinctive style focused on environmental sensitivity and dramatic natural settings. After studying at Yale and Stanford, he joined his father's firm before establishing Robert Trent Jones II Golf Course Design in 1972. His international portfolio spans over 280 courses in more than 40 countries, with particular strength in the Asia-Pacific region. Chambers Bay in University Place, Washington — site of the 2015 U.S. Open — showcased his ability to create links-style golf on an abandoned sand and gravel mine along Puget Sound. Poppy Hills on the Monterey Peninsula serves as the home course for the Northern California Golf Association. Jones Jr. has been a pioneer in environmental golf design, earning numerous awards for sustainable practices and habitat restoration.",
    designPhilosophy: "Jones Jr. emphasizes harmony between golf and nature. He designs courses that celebrate their natural environments rather than impose upon them. His approach integrates environmental stewardship with strategic playability, creating courses that are ecologically responsible while offering memorable golf experiences across diverse landscapes worldwide.",
    signatureCourses: ["Chambers Bay", "Poppy Hills", "Spanish Bay", "Princeville (Prince)", "The Links at Crowbush Cove"],
    notableFeatures: ["Environmental sensitivity", "Links-style design in unexpected settings", "Dramatic coastal and mountain routings", "Sustainable design practices"],
  },
  {
    name: "C.B. Macdonald",
    slug: "cb-macdonald",
    bornYear: 1855,
    diedYear: 1939,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 18,
    bio: "Charles Blair Macdonald was the father of American golf course architecture and built the first 18-hole course in the United States — Chicago Golf Club in 1895. Born in Niagara Falls, Ontario, he attended the University of St Andrews in Scotland where he fell in love with golf and studied the great links courses of the British Isles. Upon returning to America, Macdonald became obsessed with bringing the strategic principles of Scottish and English golf to the New World. His masterwork, National Golf Links of America on Long Island, opened in 1911 and featured template holes inspired by the greatest holes in Britain — the Redan, the Alps, the Cape, and the Eden among them. These templates became foundational concepts that architects still reference today. Macdonald also designed Yale Golf Course and Mid Ocean Club in Bermuda, and mentored Seth Raynor, who carried his template philosophy forward.",
    designPhilosophy: "Macdonald believed the best holes in golf had already been designed on the links of Britain, and his mission was to adapt these templates to American terrain. His 'ideal hole' concept — studying and replicating the strategic principles of famous holes — became the foundation of template architecture. He insisted courses should test strategy and shot-making, not merely punish poor swings.",
    signatureCourses: ["National Golf Links of America", "Chicago Golf Club", "Yale Golf Course", "Mid Ocean Club", "The Lido (destroyed)"],
    notableFeatures: ["Template hole designs (Redan, Alps, Cape, Eden)", "Strategic principles adapted from British links", "Bold, geometric bunkering", "Pioneering American course architecture"],
  },
  {
    name: "Gil Hanse",
    slug: "gil-hanse",
    bornYear: 1965,
    diedYear: null,
    nationality: "American",
    era: "Modern/Renaissance",
    totalCoursesDesigned: 40,
    bio: "Gil Hanse is one of the most acclaimed golf course architects of the 21st century, known for building the Olympic Golf Course in Rio de Janeiro for the 2016 Games and for his sensitive restorations of Golden Age classics. A graduate of Cornell University's landscape architecture program, Hanse worked with Tom Doak before establishing his own firm with design partner Jim Wagner. His original designs include Ohoopee Match Club in Georgia, Streamsong Black in Florida, and the celebrated Mossy Oak course in Mississippi. Equally renowned for his restoration work, Hanse has revitalized classics like Merion Golf Club, Los Angeles Country Club (North), and The Country Club at Brookline — the latter hosting the 2022 U.S. Open to universal acclaim. His minimalist approach and respect for existing landforms have made him the go-to architect for clubs seeking authentic, strategic golf.",
    designPhilosophy: "Hanse practices minimalism in design — moving as little earth as possible and letting the natural terrain dictate the routing and strategy. He believes the best courses appear as though they were discovered, not built. His greens are firm, fast, and full of subtle movement that rewards precision and imagination. He favors ground-game options alongside aerial approaches.",
    signatureCourses: ["Olympic Golf Course (Rio)", "Streamsong Black", "Ohoopee Match Club", "Los Angeles CC North (restoration)", "Brookline/The Country Club (restoration)"],
    notableFeatures: ["Minimalist earth-moving", "Firm, strategic greens complexes", "Ground-game friendly design", "Sensitive restoration of Golden Age courses"],
  },
  {
    name: "Tom Doak",
    slug: "tom-doak",
    bornYear: 1961,
    diedYear: null,
    nationality: "American",
    era: "Modern/Renaissance",
    totalCoursesDesigned: 35,
    bio: "Tom Doak is arguably the most intellectually rigorous golf course architect working today, known for his uncompromising minimalist philosophy and his influential book 'The Confidential Guide to Golf Courses.' A Cornell University graduate, Doak spent time in Britain studying links courses and worked briefly with Pete Dye before founding Renaissance Golf Design. Pacific Dunes at Bandon Dunes Resort in Oregon — perched on dramatic bluffs above the Pacific Ocean — is consistently ranked among the top courses in the world and launched the Bandon empire into the stratosphere. Ballyneal in Colorado, set on rolling sand hills, and Streamsong Blue in Florida further demonstrate his ability to find and celebrate the golf potential latent in remarkable sites. His Confidential Guide, which rates courses on a 0-10 scale with unflinching honesty, has made him both admired and controversial in golf architecture circles.",
    designPhilosophy: "Doak is a committed minimalist who believes great golf courses are found, not manufactured. He moves minimal earth, preserves natural contours, and routes holes to take maximum advantage of the land's existing features. His greens are wide, wild, and demand creative shotmaking. He has said that if a green looks too perfect, it probably isn't interesting enough.",
    signatureCourses: ["Pacific Dunes", "Ballyneal", "Streamsong Blue", "Cape Kidnappers", "Old Macdonald"],
    notableFeatures: ["Extreme minimalism in construction", "Wild, imaginative greens", "Links-style design on American soil", "Dramatic natural site selection"],
  },
  {
    name: "Bill Coore",
    slug: "bill-coore-ben-crenshaw",
    bornYear: 1946,
    diedYear: null,
    nationality: "American",
    era: "Modern/Renaissance",
    totalCoursesDesigned: 50,
    bio: "Bill Coore and Ben Crenshaw form the most celebrated partnership in modern golf course architecture. Coore, a North Carolina native who studied landscape architecture, handles the technical and construction aspects, while Crenshaw — a two-time Masters champion and devoted golf historian — contributes his deep understanding of classic design and feel for strategic golf. Together as Coore & Crenshaw, they have created some of the most acclaimed courses of the past 30 years. Sand Hills Golf Club in Mullen, Nebraska — routed through dramatic sand hills with no two holes alike — is widely considered the greatest course built since the Golden Age. Bandon Trails and the new Sheep Ranch at Bandon Dunes, Plantation Course at Kapalua, and Shanqin Bay in China showcase their range. Their restoration of Pinehurst No. 2, removing rough and restoring native sandy areas, was universally praised and influenced course maintenance practices worldwide.",
    designPhilosophy: "Coore & Crenshaw believe in walking the land extensively before designing a single hole, allowing the terrain to reveal the routing. Their minimalist approach moves as little earth as possible, creating courses that feel timeless and inevitable. They favor wide fairways with strategic bunkering, firm conditions that encourage the ground game, and greens complexes that offer multiple recovery options.",
    signatureCourses: ["Sand Hills Golf Club", "Bandon Trails", "Sheep Ranch", "Plantation Course at Kapalua", "Pinehurst No. 2 (restoration)"],
    notableFeatures: ["Routing-driven design from extensive site walks", "Minimalist construction philosophy", "Wide fairways with strategic options", "Restoration of native sandy landscapes"],
  },
  {
    name: "A.W. Tillinghast",
    slug: "aw-tillinghast",
    bornYear: 1874,
    diedYear: 1942,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 265,
    bio: "Albert Warren Tillinghast was one of the most brilliant and flamboyant golf course architects of the Golden Age. Born into a wealthy Philadelphia family, he traveled to St Andrews as a young man and was mentored by Old Tom Morris. 'Tilly,' as he was known, brought an artistic sensibility and perfectionist's eye to course design, creating some of America's most enduring championship venues. Winged Foot Golf Club in Mamaroneck, New York — with its punishing West Course that has hosted multiple U.S. Opens — may be his greatest achievement. Baltusrol Golf Club's Upper and Lower courses, Bethpage Black (the first publicly-owned course to host a U.S. Open), and San Francisco Golf Club further demonstrate his extraordinary range. Tillinghast was known for his extravagant lifestyle and sharp wit, and his later years saw him fall on hard times during the Great Depression. His courses, however, have only grown in stature.",
    designPhilosophy: "Tillinghast demanded that every hole present a distinct strategic challenge and believed in the concept of 'the heroic shot' — where players must decide whether to risk a bold play for birdie or take a safer line for par. His bunkering is considered among the finest ever — deep, dramatic, and precisely placed to frame strategic options. He said, 'A round of golf should provide 18 inspirations.'",
    signatureCourses: ["Winged Foot West", "Bethpage Black", "Baltusrol Lower", "San Francisco Golf Club", "Quaker Ridge"],
    notableFeatures: ["Heroic bunkering that defines strategy", "Demanding championship greens", "Strong par-4 holes as the backbone", "18 distinct hole characters per course"],
  },
  {
    name: "Seth Raynor",
    slug: "seth-raynor",
    bornYear: 1874,
    diedYear: 1926,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 50,
    bio: "Seth Raynor was C.B. Macdonald's protégé and construction foreman who became a masterful architect in his own right before his untimely death at age 51. Originally trained as a civil engineer at Princeton, Raynor had never played golf when Macdonald hired him to survey the land for the National Golf Links of America. He quickly absorbed Macdonald's template philosophy and became its most gifted practitioner. Raynor adapted the classic template holes — Redan, Alps, Short, Biarritz, Cape, Punchbowl — with a precision and boldness that many consider superior to the originals. Fishers Island Club in New York, perched on a dramatic island in Long Island Sound, is his masterpiece. Chicago Golf Club's redesign, Camargo Club in Ohio, and Mountain Lake in Florida are equally revered. His courses are characterized by geometric, sharply defined bunkering and greens that demand specific approach angles.",
    designPhilosophy: "Raynor perfected the template system inherited from Macdonald, executing classic hole designs with engineering precision and dramatic visual impact. His courses are intellectual puzzles where knowledge of the template origins unlocks the strategy. Each hole clearly rewards a specific shot shape or approach angle, and his geometric bunkering serves as both visual framing and strategic challenge.",
    signatureCourses: ["Fishers Island Club", "Chicago Golf Club (redesign)", "Camargo Club", "Mountain Lake", "Shoreacres"],
    notableFeatures: ["Perfected template hole designs", "Geometric, sharply defined bunkering", "Engineering precision in construction", "Angular greens demanding specific approach shots"],
  },
  {
    name: "George Crump",
    slug: "george-crump",
    bornYear: 1871,
    diedYear: 1918,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 1,
    bio: "George Arthur Crump is the most remarkable one-course architect in golf history. A Philadelphia hotelier and accomplished amateur golfer, Crump became obsessed with building the ultimate golf course and spent his fortune and final years creating Pine Valley Golf Club in Clementon, New Jersey. He identified a 184-acre tract of sandy, forested land in the Pine Barrens and moved into a bungalow on the property in 1912 to oversee every detail of construction. Crump consulted with leading architects including H.S. Colt, A.W. Tillinghast, George Thomas, and Alister MacKenzie during the design process. He died in 1918 before the course was fully completed — Hugh Wilson finished the final four holes. Pine Valley has been ranked the #1 golf course in the world by virtually every publication for decades, a testament to Crump's singular vision and obsessive dedication to perfection.",
    designPhilosophy: "Crump envisioned each hole as an isolated challenge surrounded by fearsome natural hazards — vast sandy wastelands, dense forests, and water features that create a heroic 'island hopping' experience from tee to green. His design demands precision on every shot; there is no rough at Pine Valley, only paradise or peril. Each hole is completely separated from the others, creating a sense of solitude and drama unique in golf.",
    signatureCourses: ["Pine Valley Golf Club"],
    notableFeatures: ["Island fairways surrounded by sandy waste", "Total isolation between holes", "Heroic carry shots over natural hazards", "No rough — only fairway or wasteland"],
  },
  {
    name: "Harry Colt",
    slug: "harry-colt",
    bornYear: 1869,
    diedYear: 1951,
    nationality: "British",
    era: "Golden Age",
    totalCoursesDesigned: 300,
    bio: "Harry Shapland Colt was one of the most influential golf course architects of the early 20th century and is often credited with professionalizing the field. A Cambridge-educated lawyer, Colt became the first secretary of Sunningdale Golf Club and designed its celebrated New Course while managing the property. He eventually left law entirely to focus on golf architecture, forming a partnership with Charles Hugh Alison and John Morrison that produced hundreds of courses worldwide. Colt pioneered the use of detailed plan drawings in course design — previously architects worked primarily on-site — bringing systematic rigor to the profession. His work at Sunningdale (New), Royal Portrush (Dunluce), Wentworth, and Pine Valley (consulting) established him as one of the most important figures in golf design history. His influence extended globally through Alison, who took their design principles to Japan and other Asian countries.",
    designPhilosophy: "Colt believed in strategic design that rewarded thought and precision over raw power. He pioneered dog-leg holes that offered risk-reward choices and designed greens with subtle contours that required careful study. His approach to bunkering was to place hazards where they would challenge the better player while leaving a bail-out route for higher handicappers. He emphasized that the best courses should be enjoyable walks through beautiful settings.",
    signatureCourses: ["Sunningdale New", "Royal Portrush (Dunluce)", "Wentworth West", "Pine Valley (consulting)", "Swinley Forest"],
    notableFeatures: ["Pioneered plan-drawn course design", "Strategic dog-leg holes", "Subtle green contours", "Beautiful, naturalistic routing through woodlands"],
  },
  {
    name: "George Thomas",
    slug: "george-thomas",
    bornYear: 1873,
    diedYear: 1932,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 15,
    bio: "George Clifford Thomas Jr. was a Philadelphia-born polymath — champion rose breeder, ornithologist, World War I aviator, and author — who produced some of the finest golf courses in Southern California. Born into wealth, Thomas designed courses purely for the love of the game and never accepted payment for his work. His masterpiece, Riviera Country Club in Pacific Palisades, has hosted the U.S. Open, PGA Championship, and numerous PGA Tour events, and its challenging par-4 10th and driveable par-4 10th are among the most studied holes in architecture. Los Angeles Country Club North, redesigned by Gil Hanse and host of the 2023 U.S. Open, was originally routed by Thomas. Bel-Air Country Club, clinging to dramatic canyon terrain, further showcases his ability to route through challenging topography. Thomas authored 'Golf Architecture in America,' one of the field's foundational texts.",
    designPhilosophy: "Thomas believed in strategic variety — he wanted every hole to offer multiple paths to the green and to reward the thinking player. He was an early advocate for the 'short par 4' as a strategic weapon, creating driveable holes where the risk-reward calculus demands careful consideration. His courses feature dramatic bunkering and green complexes that provide visual beauty alongside strategic substance.",
    signatureCourses: ["Riviera Country Club", "Los Angeles Country Club North", "Bel-Air Country Club", "Ojai Valley Inn", "North Ranch CC"],
    notableFeatures: ["Strategic short par 4s", "Dramatic canyon and hillside routing", "Bold, artistic bunkering", "Never accepted payment for designs"],
  },
  {
    name: "Tom Morris Sr.",
    slug: "tom-morris-sr",
    bornYear: 1821,
    diedYear: 1908,
    nationality: "Scottish",
    era: "Early/Pre-Golden Age",
    totalCoursesDesigned: 75,
    bio: "Thomas Mitchell Morris Sr., known universally as Old Tom Morris, was the founding father of golf course design and one of the most important figures in golf history. Born in St Andrews, he was a four-time Open Championship winner, greenkeeper of the Royal and Ancient Golf Club, and the patriarch of golf course architecture. Old Tom designed and remodeled courses across Scotland and beyond, including Prestwick (where the first Open was played), Royal Dornoch, Muirfield, Royal County Down, and Carnoustie. His approach was rooted in the natural links landscape — he shaped existing terrain rather than manufacturing features, establishing principles that the minimalist movement would champion over a century later. His shop beside the 18th green at St Andrews remains a landmark, and his grave in the cathedral cemetery is a pilgrimage site for golf lovers worldwide.",
    designPhilosophy: "Old Tom worked with the land as he found it, shaping natural dunes and hollows into golf holes rather than imposing artificial features. His designs reflect the earliest philosophy of golf architecture — that the game should be played across terrain naturally suited to it, with bunkers placed where sheep sheltered from the wind and greens sited on naturally flat plateaus among the dunes.",
    signatureCourses: ["The Old Course at St Andrews (modifications)", "Royal Dornoch", "Muirfield", "Royal County Down", "Prestwick"],
    notableFeatures: ["Natural links shaping", "Minimal earthmoving", "Strategic use of existing dunes", "Foundation of golf architecture as a discipline"],
  },
  {
    name: "Arnold Palmer",
    slug: "arnold-palmer",
    bornYear: 1929,
    diedYear: 2016,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 300,
    bio: "Arnold Daniel Palmer, 'The King' of golf, brought his charisma and competitive fire to golf course design through Arnold Palmer Design Company. The seven-time major champion and cultural icon began designing courses in the 1970s and created over 300 layouts worldwide. Palmer's courses reflect his playing style — bold, aggressive, and entertaining. Tralee Golf Links in Ireland, routed along dramatic Atlantic cliffs, is considered his finest work. Bay Hill Club & Lodge in Orlando, which he owned and where the Arnold Palmer Invitational is held annually, became his home course and personal laboratory. Palmer believed golf should be fun and accessible, and his designs typically offer generous fairways with strategic challenges closer to the green. His courses span 37 countries and five continents.",
    designPhilosophy: "Palmer designed courses that reflected his go-for-broke playing style — big, bold layouts that encourage aggressive play and reward the daring shot. He believed golf should be entertaining and accessible, with wide fairways off the tee that funnel into more demanding approaches. His courses are designed to create exciting moments and memorable finishing holes.",
    signatureCourses: ["Tralee Golf Links", "Bay Hill Club & Lodge", "Thracian Cliffs", "King & Bear (with Nicklaus)", "Lahinch (redesign)"],
    notableFeatures: ["Bold, aggressive routing", "Generous fairways with tough approaches", "Dramatic coastal and clifftop settings", "Entertaining risk-reward finishing holes"],
  },
  {
    name: "Rees Jones",
    slug: "rees-jones",
    bornYear: 1941,
    diedYear: null,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 200,
    bio: "Rees Jones, the younger son of Robert Trent Jones Sr., earned the nickname 'The Open Doctor' — the same title once held by his father — for his extensive work preparing courses for major championships. A Yale graduate and trained landscape architect, Jones has designed and remodeled over 200 courses. His championship preparation work is unmatched: Bethpage Black for the 2002 and 2009 U.S. Opens, Torrey Pines South for the 2008 U.S. Open, Hazeltine National for the 2016 Ryder Cup, and Congressional for multiple events. His original designs include Nantucket Golf Club, Atlantic Golf Club in the Hamptons, and Cascata in Las Vegas. Jones approaches each project with an engineer's precision and a championship host's understanding of what makes courses both fair and demanding at the highest level.",
    designPhilosophy: "Jones designs courses that are fair, demanding, and Championship-ready. He believes in clear sight lines, honest hazards, and greens complexes that reward precision while offering recovery options. His renovation work focuses on restoring strategic integrity while updating courses for the modern game's distance and technology advances.",
    signatureCourses: ["Nantucket Golf Club", "Atlantic Golf Club", "Cascata", "Bethpage Black (renovation)", "Torrey Pines South (renovation)"],
    notableFeatures: ["Championship-caliber preparation", "Fair but demanding hazard placement", "Clear sight lines and honest visuals", "Modern updates to classic venues"],
  },
  {
    name: "Mike Strantz",
    slug: "mike-strantz",
    bornYear: 1955,
    diedYear: 2005,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 10,
    bio: "Mike Strantz was a supremely talented golf course architect whose career was tragically cut short by cancer at age 50. A gifted artist who painted detailed watercolor renderings of his designs, Strantz studied under Tom Fazio before striking out on his own. Despite completing only about 10 courses, his work is extraordinary — Tobacco Road in Sanford, North Carolina, is unlike anything else in golf, a wild, tumbling journey through former sand quarries with blind shots, massive bunkers, and exhilarating elevation changes. Tot Hill Farm, also in North Carolina, features a stunning 'volcano green' and equally bold design. Royal New Kent in Virginia recreated links-style golf in the Virginia countryside. Strantz designed each hole as a painting, and his courses are noted for their dramatic visual composition and artistic bunkering. He is widely mourned as one of the great what-ifs in golf architecture.",
    designPhilosophy: "Strantz approached each hole as a work of art, composing dramatic visual scenes with bold bunkering, extreme elevation changes, and unconventional features. He believed golf should be thrilling and emotional, creating courses that surprise and delight at every turn. His designs challenge conventional thinking about what a golf hole can look like while maintaining strategic integrity.",
    signatureCourses: ["Tobacco Road", "Tot Hill Farm", "Royal New Kent", "Caledonia Golf & Fish Club", "True Blue"],
    notableFeatures: ["Artistic, painterly approach to design", "Extreme elevation changes", "Dramatic, unconventional bunkering", "Bold use of former quarry and industrial sites"],
  },
  {
    name: "Herbert Fowler",
    slug: "herbert-fowler",
    bornYear: 1856,
    diedYear: 1941,
    nationality: "British",
    era: "Golden Age",
    totalCoursesDesigned: 50,
    bio: "Herbert Fowler was a distinguished English golf course architect best known for creating two of the finest heathland courses in the world. A scratch golfer and cricket first-class player, Fowler came to golf architecture relatively late in life but produced work of extraordinary quality. Walton Heath Old Course, set on the Surrey heathland south of London, has hosted major professional events and remains one of England's finest inland courses. The Berkshire, with its Red and Blue courses routed through heather and pine, is considered his dual masterpiece. Fowler's ability to create strategic, beautiful golf on heathland terrain — sandy soil covered with heather, gorse, and pine trees — placed him at the forefront of the heathland movement that produced many of London's finest courses. He also worked internationally, contributing to the design of Eastward Ho! in Massachusetts and consulting in Ireland and Europe.",
    designPhilosophy: "Fowler excelled at heathland design, creating courses that harmonized with the natural beauty of heather, pine, and sandy soil landscapes. He believed in strategic variety, with each hole presenting a unique challenge. His bunkering was thoughtful and proportional, and his green sites took advantage of natural undulations in the terrain. He valued pace of play and enjoyable walking routes.",
    signatureCourses: ["Walton Heath Old", "The Berkshire (Red & Blue)", "Saunton East", "Westward Ho! (redesign)", "Cruden Bay"],
    notableFeatures: ["Mastery of heathland design", "Strategic variety across 18 holes", "Proportional, well-placed bunkering", "Beautiful walking courses through natural terrain"],
  },
  {
    name: "Charles Hugh Alison",
    slug: "charles-hugh-alison",
    bornYear: 1882,
    diedYear: 1952,
    nationality: "British",
    era: "Golden Age",
    totalCoursesDesigned: 80,
    bio: "Charles Hugh Alison was Harry Colt's partner and the architect who brought strategic British design principles to Japan, Australia, and East Asia. While Colt focused on European projects, Alison traveled extensively, spending months at a time in Asia where he created courses of extraordinary quality. Hirono Golf Club near Kobe, Japan, is widely considered the finest course in Asia and one of the best in the world — its dramatic bunkering and strategic routing through pine-forested hills set the standard for Japanese golf. Tokyo Golf Club, Kasumigaseki East, and Kawana (Fuji Course) further demonstrate his Asian legacy. In the United States, his work includes the acclaimed renovation of Milwaukee Country Club and consulting at several prestigious venues. Alison's detailed architectural drawings, sent by mail to overseas construction teams, were models of precision that influenced how golf architecture could be practiced across continents.",
    designPhilosophy: "Alison combined the strategic principles of British design — particularly Colt's emphasis on thought over power — with a deep sensitivity to local landscapes and cultures. His courses abroad were not copies of British originals but rather adaptations that honored local terrain and conditions. He was renowned for his deep, dramatic bunkers (known as 'Alison bunkers' in Japan) and demanding approach shots.",
    signatureCourses: ["Hirono Golf Club", "Tokyo Golf Club", "Kasumigaseki East", "Kawana (Fuji Course)", "Milwaukee Country Club"],
    notableFeatures: ["Deep 'Alison bunkers'", "Strategic design adapted to Asian landscapes", "Detailed architectural drawings for remote construction", "Bridging British and international design traditions"],
  },
  {
    name: "Hugh Wilson",
    slug: "hugh-wilson",
    bornYear: 1879,
    diedYear: 1925,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 5,
    bio: "Hugh Irvine Wilson was the inspired amateur architect behind Merion Golf Club's East Course, one of the most revered courses in the world. An insurance broker and accomplished golfer from Philadelphia, Wilson was selected by Merion's board to design their new course despite having no architectural training. He traveled to Britain to study the great courses and returned to create a masterpiece on just 120 acres — remarkably compact by championship standards. Merion East has hosted more USGA championships than any other course, including Bobby Jones's completion of the Grand Slam there in 1930. Its iconic 'white wicker basket' flagsticks and distinctive bunkering — nearly 120 bunkers on a tight routing — make it instantly recognizable. Wilson also completed Pine Valley's final four holes after George Crump's death and designed Merion's West Course. His untimely death at 46 cut short a career of unlimited promise.",
    designPhilosophy: "Wilson demonstrated that great golf architecture could be achieved on compact acreage through brilliant routing and relentless attention to detail. His courses demand precise iron play and thoughtful course management rather than length. Every bunker at Merion serves a strategic purpose, and his green complexes are among the most demanding in championship golf.",
    signatureCourses: ["Merion East", "Merion West", "Pine Valley (final 4 holes)", "Cobb's Creek"],
    notableFeatures: ["Brilliant compact routing on minimal acreage", "Dense, strategic bunkering", "Demanding iron-play courses", "White wicker basket flagsticks at Merion"],
  },
  {
    name: "Perry Maxwell",
    slug: "perry-maxwell",
    bornYear: 1879,
    diedYear: 1952,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 70,
    bio: "James Perry Maxwell was a Kentucky-born architect whose rolling, contoured greens have earned him a devoted following among golf architecture enthusiasts. A banker who transitioned to golf design, Maxwell created his finest original works in Oklahoma and the Great Plains before gaining national recognition. Prairie Dunes Country Club in Hutchinson, Kansas — later extended by his son Press — is his masterpiece, a windswept links-style course through sand hills and native grasses. His most lasting contributions may be his green redesigns at Augusta National, where Alister MacKenzie's original green contours were significantly altered by Maxwell in the 1930s — the famous slopes and ridges that define holes like the 10th and 13th carry Maxwell's signature. Colonial Country Club in Fort Worth and Southern Hills in Tulsa are also Maxwell courses that regularly host PGA Tour and major championship events.",
    designPhilosophy: "Maxwell was obsessed with greens — specifically, bold contours and ridges that create distinct sections on putting surfaces and demand precise approach shots to specific quadrants. His 'Maxwell rolls' — undulations that appear natural but strategically divide greens into challenging pin positions — are his enduring legacy. He believed the green complex was where a hole's strategy was ultimately expressed.",
    signatureCourses: ["Prairie Dunes", "Southern Hills", "Colonial Country Club", "Augusta National (green redesigns)", "Crystal Downs (with MacKenzie)"],
    notableFeatures: ["Bold 'Maxwell rolls' on greens", "Dramatic green contours and ridges", "Prairie and plains design expertise", "Green redesign work at Augusta National"],
  },
  {
    name: "Arthur Hills",
    slug: "arthur-hills",
    bornYear: 1930,
    diedYear: 2021,
    nationality: "American",
    era: "Modern",
    totalCoursesDesigned: 200,
    bio: "Arthur Hills was a prolific American golf course architect who designed and renovated more than 200 courses across the United States and internationally over a five-decade career. A graduate of the University of Michigan with a degree in landscape architecture, Hills established his firm in Toledo, Ohio and built a reputation for creating beautiful, playable courses that blend seamlessly with their natural surroundings. Palmetto Dunes (Arthur Hills Course) in Hilton Head, Longbow Golf Club in Arizona, and The Tidewater Golf Club in Myrtle Beach showcase his ability to create memorable layouts across diverse terrains. Hills was particularly skilled at resort and public-access course design, creating layouts that were visually dramatic and enjoyable for golfers of all skill levels. He received numerous awards from the American Society of Golf Course Architects.",
    designPhilosophy: "Hills believed in creating visually beautiful courses that were enjoyable for golfers of all abilities. His designs emphasize natural aesthetics, with holes framed by native vegetation and water features that enhance both beauty and strategy. He favored clear sight lines from tee to green and generous bail-out areas alongside demanding championship-level challenges.",
    signatureCourses: ["Palmetto Dunes (Arthur Hills Course)", "Longbow Golf Club", "The Tidewater Golf Club", "Bay Harbor Golf Club", "Boyne Highlands (Arthur Hills Course)"],
    notableFeatures: ["Visually dramatic resort courses", "Natural vegetation framing", "Playable for all skill levels", "Strategic water features"],
  },
  {
    name: "Gary Player",
    slug: "gary-player",
    bornYear: 1935,
    diedYear: null,
    nationality: "South African",
    era: "Modern",
    totalCoursesDesigned: 400,
    bio: "Gary Player, one of only five golfers to win all four major championships (the Career Grand Slam), has parlayed his global fame and travel into one of the world's largest golf design portfolios. Through Gary Player Design, he has created over 400 courses in 41 countries across five continents, with particular expertise in African, Middle Eastern, and Asian markets. Player's courses often feature dramatic topography and stunning landscapes. The Links at Fancourt in South Africa hosted the 2003 Presidents Cup and is considered one of the finest courses on the African continent. His work at Lost City Golf Course in Sun City, with its crocodile-inhabited water hazard, demonstrates his flair for the dramatic. Player's designs prioritize visual impact and memorable moments while maintaining fair, strategic challenges throughout.",
    designPhilosophy: "Player designs courses that create memorable experiences through dramatic landscapes and bold features. Drawing on his experience playing courses worldwide for over 60 years, he emphasizes strategic variety, visual drama, and conditions suited to each course's climate and culture. He believes golf should test all aspects of the game while creating indelible memories.",
    signatureCourses: ["The Links at Fancourt", "Lost City Golf Course", "The Chateau Golf Club (China)", "Legend Golf & Safari Resort", "Al Mouj Golf (Oman)"],
    notableFeatures: ["Global design portfolio across 41 countries", "Dramatic landscapes and bold features", "Courses adapted to diverse climates", "Memorable signature holes"],
  },
  {
    name: "Ben Crenshaw",
    slug: "ben-crenshaw",
    bornYear: 1952,
    diedYear: null,
    nationality: "American",
    era: "Modern/Renaissance",
    totalCoursesDesigned: 50,
    bio: "Harvey Penick's most famous pupil and a two-time Masters champion, Ben Crenshaw has channeled his passion for golf history into a celebrated career as a golf course architect alongside partner Bill Coore. Crenshaw's deep knowledge of classic golf design — he is an avid collector of golf architecture books and has studied the great courses of the British Isles extensively — provides the aesthetic and strategic vision for the Coore & Crenshaw partnership. While Coore handles the technical construction details, Crenshaw contributes an intuitive feel for what makes a hole memorable and strategically engaging. His playing experience at the highest level, including two green jackets from Augusta National, gives him unique insight into what challenges and delights golfers. See the Coore & Crenshaw entry for their combined body of work.",
    designPhilosophy: "Crenshaw brings a historian's reverence for Golden Age design and a champion's understanding of strategic golf to his partnership with Bill Coore. He believes courses should honor the land and the game's traditions, creating timeless layouts that feel as though they have existed for a century. His intuitive feel for green contours, bunker placement, and routing derives from a lifetime studying and playing the world's greatest courses.",
    signatureCourses: ["Sand Hills Golf Club", "Bandon Trails", "Sheep Ranch", "Plantation Course at Kapalua", "Pinehurst No. 2 (restoration)"],
    notableFeatures: ["Deep knowledge of golf history and classic design", "Intuitive green complex design", "Champion's perspective on strategy", "Reverence for Golden Age principles"],
  },
  {
    name: "Bobby Jones",
    slug: "bobby-jones",
    bornYear: 1902,
    diedYear: 1971,
    nationality: "American",
    era: "Golden Age",
    totalCoursesDesigned: 2,
    bio: "Robert Tyre 'Bobby' Jones Jr. is the greatest amateur golfer who ever lived — winner of the Grand Slam in 1930 (all four major championships in a single year), a feat never repeated. After retiring from competitive golf at 28, Jones co-founded Augusta National Golf Club with Clifford Roberts and collaborated with Alister MacKenzie on its design. Jones's playing brilliance directly shaped Augusta's strategic concepts — he wanted a course that would reward imagination and shot-making over brute strength, with every hole offering a risk-reward choice that could determine a player's fate. Augusta National and The Masters tournament it hosts annually have become the most iconic venue and event in golf. Jones also designed Peachtree Golf Club in Atlanta with Robert Trent Jones Sr., creating a deeply strategic layout that reflected his playing philosophy. His contribution to golf architecture, while limited in volume, is incalculable in influence.",
    designPhilosophy: "Jones believed golf should be a test of skill, strategy, and temperament — not simply a punishment for poor shots. Augusta National was designed so that the bold, imaginative player would be rewarded and the timid player would never score well. He wanted courses that generated excitement and drama, where the outcome of any round could change on a single hole.",
    signatureCourses: ["Augusta National (with MacKenzie)", "Peachtree Golf Club (with RTJ Sr.)"],
    notableFeatures: ["Risk-reward strategic design", "Wide fairways with demanding green complexes", "Courses designed from a champion's perspective", "Every hole offers a dramatic choice"],
  },
  {
    name: "Dick Wilson",
    slug: "dick-wilson",
    bornYear: 1904,
    diedYear: 1965,
    nationality: "American",
    era: "Post-War",
    totalCoursesDesigned: 80,
    bio: "Robert Richard 'Dick' Wilson was one of the finest American golf course architects of the post-war era, known for bold, distinctive designs that combined dramatic bunkering with strategic sophistication. Based in Delray Beach, Florida, Wilson created some of the most celebrated courses in the Southeast and beyond. Doral's Blue Monster in Miami, with its fearsome 18th hole featuring a massive water hazard, became one of the PGA Tour's most iconic venues. Meadow Brook Club on Long Island, Pine Tree Golf Club in Florida, and NCR Country Club (South) in Ohio are among his finest works. Wilson's design associate, Joe Lee, continued his firm after Wilson's early death at 60, and many of Wilson's courses have been restored and updated by modern architects who recognize the strategic brilliance of his original designs.",
    designPhilosophy: "Wilson created bold, dramatic courses with strategically placed bunkers that demanded thoughtful play. His designs feature strong bunkering patterns that frame hole strategies and dramatically shaped greens that reward precise approach shots. He believed a great course should be visually exciting and strategically demanding in equal measure.",
    signatureCourses: ["Doral (Blue Monster)", "Pine Tree Golf Club", "Meadow Brook Club", "NCR Country Club South", "Bay Hill (original)"],
    notableFeatures: ["Bold, dramatic bunkering", "Strategic green complexes", "Iconic finishing holes", "Influential Southeast Florida designs"],
  },
];

export async function POST(request: NextRequest) {
  const authError = await checkAdminAuth(request);
  if (authError) return authError;

  try {
    const results = [];
    for (const arch of ARCHITECTS) {
      const architect = await prisma.architect.upsert({
        where: { slug: arch.slug },
        update: {
          name: arch.name,
          bornYear: arch.bornYear,
          diedYear: arch.diedYear,
          nationality: arch.nationality,
          bio: arch.bio,
          designPhilosophy: arch.designPhilosophy,
          signatureCourses: arch.signatureCourses,
          notableFeatures: arch.notableFeatures,
          era: arch.era,
          totalCoursesDesigned: arch.totalCoursesDesigned,
          imageUrl: null,
        },
        create: {
          name: arch.name,
          slug: arch.slug,
          bornYear: arch.bornYear,
          diedYear: arch.diedYear,
          nationality: arch.nationality,
          bio: arch.bio,
          designPhilosophy: arch.designPhilosophy,
          signatureCourses: arch.signatureCourses,
          notableFeatures: arch.notableFeatures,
          era: arch.era,
          totalCoursesDesigned: arch.totalCoursesDesigned,
          imageUrl: null,
        },
      });
      results.push({ id: architect.id, name: architect.name, slug: architect.slug });
    }

    return NextResponse.json({
      message: `Seeded ${results.length} architects`,
      architects: results,
    }, { status: 201 });
  } catch (err) {
    console.error("Architect seed error:", err);
    return NextResponse.json(
      { error: "Failed to seed architects" },
      { status: 500 }
    );
  }
}
